// Enhanced product descriptions for better UX
// These supplement the descriptions from Stripe

import { ProjectType } from '@/types/product';

export const productDescriptionEnhancements: Record<string, string> = {
  // Flight Offset specific descriptions
  'flight_offset': 'Offset the carbon emissions from your flights by supporting verified environmental projects. Each credit neutralizes the CO₂ generated by air travel.',

  // Yearly Offset descriptions
  'yearly_subscription': 'Automatically offset your carbon footprint every month with verified carbon credits. Set it and forget it while making a positive environmental impact.',

  // Subscription tier descriptions
  'subscription_basic': 'Perfect for individuals looking to offset their basic carbon footprint from daily activities.',
  'subscription_standard': 'Ideal for households or individuals with moderate emissions from transportation and energy use.',
  'subscription_premium': 'Comprehensive offset solution for those committed to carbon neutrality with higher emissions.',
};

export const projectTypeDescriptions: Record<ProjectType, string> = {
  [ProjectType.FLIGHT_OFFSET]: 'Support verified projects that directly counteract aviation emissions through reforestation and renewable energy initiatives.',
  [ProjectType.AFFORESTATION]: 'Plant new forests that absorb CO₂ from the atmosphere while creating habitats for wildlife and supporting local communities.',
  [ProjectType.REFORESTATION]: 'Restore degraded forests to their natural state, capturing carbon while protecting biodiversity and water resources.',
  [ProjectType.ENERGY_WASTE]: 'Support clean energy projects that reduce reliance on fossil fuels and promote sustainable energy solutions.',
  [ProjectType.HYDROELECTRIC]: 'Fund renewable hydroelectric projects that generate clean electricity without carbon emissions.',
};

/**
 * Get an enhanced description for a product
 */
export function getEnhancedDescription(
  originalDescription: string,
  projectType?: ProjectType,
  productName?: string
): string {
  // If original description is comprehensive, use it
  if (originalDescription && originalDescription.length > 50) {
    return originalDescription;
  }

  // Check for specific product type enhancements
  if (projectType === ProjectType.FLIGHT_OFFSET) {
    return productDescriptionEnhancements.flight_offset;
  }

  if (productName?.toLowerCase().includes('yearly') || productName?.toLowerCase().includes('subscription')) {
    return productDescriptionEnhancements.yearly_subscription;
  }

  // Fall back to project type description
  if (projectType && projectTypeDescriptions[projectType]) {
    return projectTypeDescriptions[projectType];
  }

  // Last resort: return original or a generic message
  return originalDescription || 'Verified carbon credits that support environmental projects around the world.';
}
